### ISSUE TITLE
Accidental beta tagged as main

### ISSUE THREAD

**Issue by jcapriot** [conda-forge/simpeg-feedstock#8]
Hi @conda-forge/core,

Please either remove the file named ``noarch/simpeg-0.14.0b0-py_0.tar.bz2`` that was tagged as ``main``, or move it to ``broken``

because:

I accidentally pushed the beta version with a ``main`` tag, in the process of figuring out the tagging process.

Regards,

**Comment by jcapriot** [comment]
@beckermr, thanks for your help on gitter

**Comment by beckermr** [comment]
Alright. Marked as broken. Closing this issue.
